version: '2'
services:
    iservices-app:
        image: iservices
        external_links:
            - iservices-mysql:mysql
            - iservices-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/iservices?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    iservices-mysql:
        extends:
            file: mysql.yml
            service: iservices-mysql
    iservices-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: iservices-elasticsearch
